// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaaXNTMVh_l44QcCZnieX_4xSwmZwIWk8',
    appId: '1:70592790869:web:88411c7e114f0af8d36fdc',
    messagingSenderId: '70592790869',
    projectId: 'reaction-chat-e11c5',
    authDomain: 'reaction-chat-e11c5.firebaseapp.com',
    storageBucket: 'reaction-chat-e11c5.appspot.com',
    measurementId: 'G-ZZXMBL8YW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYFsyJhS0cJmCseo2qJh3ZEEzQ7odjlfY',
    appId: '1:70592790869:android:cc56c6a2afe3f3b6d36fdc',
    messagingSenderId: '70592790869',
    projectId: 'reaction-chat-e11c5',
    storageBucket: 'reaction-chat-e11c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWsg01fyGP174l811Iyhx9813zyA6oE-Q',
    appId: '1:70592790869:ios:2da154bb648ae693d36fdc',
    messagingSenderId: '70592790869',
    projectId: 'reaction-chat-e11c5',
    storageBucket: 'reaction-chat-e11c5.appspot.com',
    iosClientId:
        '70592790869-cgt5ag2f7jcm61gcdrd8bjcub06c4hol.apps.googleusercontent.com',
    iosBundleId: 'com.example.reactionchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWsg01fyGP174l811Iyhx9813zyA6oE-Q',
    appId: '1:70592790869:ios:2da154bb648ae693d36fdc',
    messagingSenderId: '70592790869',
    projectId: 'reaction-chat-e11c5',
    storageBucket: 'reaction-chat-e11c5.appspot.com',
    iosClientId:
        '70592790869-cgt5ag2f7jcm61gcdrd8bjcub06c4hol.apps.googleusercontent.com',
    iosBundleId: 'com.example.reactionchat',
  );
}
